### ISSUE TITLE
Please add AMD Support like Require JS

### ISSUE THREAD

**Issue by mariusfilipowski** [mikehostetler/amplify#66] opened 2012-08-15 06:38 UTC
It would be cool to use amplify as an module without globals that can be "required" with AMD. JQuery, Knockout etc. also support such scenarios and the implementation is not difficult. 
See https://github.com/umdjs/umd/ for implementation tips...

**Comment by scottgonzalez** [comment] 2012-08-15 15:10
Duplicate of #43.

**Closed as completed by scottgonzalez** 2012-08-15 15:10 UTC
