### ISSUE TITLE
Parsing errors with ASP .NET MVC 4 Minifier

### ISSUE THREAD

**Issue by georgiosd** [mikehostetler/amplify#71] opened 2012-09-24 10:39 UTC
Looks like the regex in userData has to be changed to /[^-._0-9A-Za-z\xb7\xc0-\xd6\xd8-\xf6\xf8-\u037d\u037f-\u1fff\u200c-\u200d\u203f\u2040\u2070-\u218f]/g

(Escaped first dash and added a zero to u37f)

**Comment by scottgonzalez** [comment] 2012-09-24 14:26
Duplicate of #65.

**Closed as completed by scottgonzalez** 2012-09-24 14:26 UTC
